stages:
  - init
  - validate
  - plan
  - apply

variables:
  TF_VERSION: "1.9.6"
  AWS_CREDENTIALS_ID: "aws-credentials-id"
  ENVIRONMENT: "dev"

before_script:
  - export TF_VAR_environment=${ENVIRONMENT}
  - terraform --version
  - terraform init -backend-config="${ENVIRONMENT}.tfbackend"

init:
  stage: init
  script:
    - terraform init -backend-config="${ENVIRONMENT}.tfbackend"

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -var-file="${ENVIRONMENT}.tfvars" -out=tfplan

apply_dev_staging:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  environment:
    name: ${ENVIRONMENT}
  only:
    - dev
    - staging

apply_prod:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  environment:
    name: production
  when: manual
  only:
    - prod
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
      allow_failure: false
