name: Deploy to AWS

on:
  push:
    paths:
        - 'modulo7/ej1/**'
    branches:
      - master

jobs:
  ansible_terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modulo7/ej1
    steps:
      - name: clone_repo
        uses: actions/checkout@v3

      - name: install_terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: "1.9.6"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem 

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Plan
        env:
          TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }} # Public key from GitHub secrets
          TF_VAR_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # Private key from GitHub secrets
          TF_VAR_private_key_file_path: "~/.ssh/key.pem"
        run: |
          terraform plan -var-file terraform.tfvars

      - name: Terraform Apply
        env:
          TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }} # Public key from GitHub secrets
          TF_VAR_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # Private key from GitHub secrets
          TF_VAR_private_key_file_path: "~/.ssh/key.pem"
          TF_LOG: "DEBUG"
        run: |
          terraform apply -var-file terraform.tfvars -auto-approve
