name: Deploy to AWS

on:
  push:
    paths:
        - 'modulo7/ej1/**'
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modulo7/ej1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }} # Public key from GitHub secrets
          TF_VAR_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # Private key from GitHub secrets
        run: terraform plan -var-file terraform.tfvars

      - name: Terraform Apply
        env:
          TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }} # Public key from GitHub secrets
          TF_VAR_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # Private key from GitHub secrets
        run: terraform apply -var-file terraform.tfvars -auto-approve
