name: "Despliegue de ejercicio práctico"

on:
  push:
    paths:
      - 'modulo6/**'
      - '.github\workflows\ansible_deploy1.yml'
    branches:
      - master
    
env:
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRETS_ACCESS_KEY }}'

jobs:
  terraform :
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Permisos para crear issues
    steps: 
      - name: clone_repo
        uses: actions/checkout@v3

      - name: install_terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: "1.9.6"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: terraform_init
        run: |
          terraform init

      - name: terraform_plan
        run: |
          terraform plan -var-file $tf_vars_file

      - name: terraform_apply
        run: |
          terraform apply -var-file $tf_vars_file -auto-approve

  